// Code generated by go-swagger; DO NOT EDIT.

package todos

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/bwangelme/SwaggerDemo/models"
)

// DeleteIDNoContentCode is the HTTP code returned for type DeleteIDNoContent
const DeleteIDNoContentCode int = 204

/*DeleteIDNoContent Deleted

swagger:response deleteIdNoContent
*/
type DeleteIDNoContent struct {
}

// NewDeleteIDNoContent creates DeleteIDNoContent with default headers values
func NewDeleteIDNoContent() *DeleteIDNoContent {

	return &DeleteIDNoContent{}
}

// WriteResponse to the client
func (o *DeleteIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*DeleteIDDefault error

swagger:response deleteIdDefault
*/
type DeleteIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteIDDefault creates DeleteIDDefault with default headers values
func NewDeleteIDDefault(code int) *DeleteIDDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete ID default response
func (o *DeleteIDDefault) WithStatusCode(code int) *DeleteIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete ID default response
func (o *DeleteIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete ID default response
func (o *DeleteIDDefault) WithPayload(payload *models.Error) *DeleteIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete ID default response
func (o *DeleteIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
