// Code generated by go-swagger; DO NOT EDIT.

package todos

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/bwangelme/SwaggerDemo/models"
)

// PostCreatedCode is the HTTP code returned for type PostCreated
const PostCreatedCode int = 201

/*PostCreated Created

swagger:response postCreated
*/
type PostCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Item `json:"body,omitempty"`
}

// NewPostCreated creates PostCreated with default headers values
func NewPostCreated() *PostCreated {

	return &PostCreated{}
}

// WithPayload adds the payload to the post created response
func (o *PostCreated) WithPayload(payload *models.Item) *PostCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post created response
func (o *PostCreated) SetPayload(payload *models.Item) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PostDefault error

swagger:response postDefault
*/
type PostDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostDefault creates PostDefault with default headers values
func NewPostDefault(code int) *PostDefault {
	if code <= 0 {
		code = 500
	}

	return &PostDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post default response
func (o *PostDefault) WithStatusCode(code int) *PostDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post default response
func (o *PostDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post default response
func (o *PostDefault) WithPayload(payload *models.Error) *PostDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post default response
func (o *PostDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
