// Code generated by go-swagger; DO NOT EDIT.

package todos

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/bwangelme/SwaggerDemo/models"
)

// PutIDOKCode is the HTTP code returned for type PutIDOK
const PutIDOKCode int = 200

/*PutIDOK ok

swagger:response putIdOK
*/
type PutIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Item `json:"body,omitempty"`
}

// NewPutIDOK creates PutIDOK with default headers values
func NewPutIDOK() *PutIDOK {

	return &PutIDOK{}
}

// WithPayload adds the payload to the put Id o k response
func (o *PutIDOK) WithPayload(payload *models.Item) *PutIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put Id o k response
func (o *PutIDOK) SetPayload(payload *models.Item) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PutIDDefault error

swagger:response putIdDefault
*/
type PutIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutIDDefault creates PutIDDefault with default headers values
func NewPutIDDefault(code int) *PutIDDefault {
	if code <= 0 {
		code = 500
	}

	return &PutIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the put ID default response
func (o *PutIDDefault) WithStatusCode(code int) *PutIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the put ID default response
func (o *PutIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the put ID default response
func (o *PutIDDefault) WithPayload(payload *models.Error) *PutIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put ID default response
func (o *PutIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
